name: mastermind build
on: [push]
permissions:
  contents: write
jobs:
  build-deploy:
    name: Build Website and Deploy on Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Install npm dependencies
        run: npm install
      - name: Build Website
        run: |
          mkdir dist
          cp index.html dist
          cp game.js dist
      - name: Build Tailwind CSS
        run: npx tailwindcss -i tailwind.css -o dist/style.css --minify
      - name: Deploy on Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}